### ISSUE TITLE
wrong absolute path in docker-compose.yml

### ISSUE THREAD

**Issue by sebastien-genete** [sachua/mlflow-docker-compose#40]
In order to start mysql, the volume "**dbdata**" needs to be linked to  **./**dbdata and not only dbdata
The dot is important.

If not, we get this error:

```
mlflow_server  | 2023/01/16 12:12:33 WARNING mlflow.store.db.utils: SQLAlchemy engine could not be created. The following exception is caught.
mlflow_server  | (pymysql.err.OperationalError) (1045, "Access denied for user 'mlflow_user'@'172.30.0.5' (using password: YES)"
```

A working setting : 
```
    db:
        restart: always
        image: mysql/mysql-server@sha256:fcbe88694872e88ae406bc69540211505eae922a182690d85be6af1a48e5ca0a
        container_name: mlflow_db
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - ./dbdata:/var/lib/mysql
```
